version: '3.2'
services:
    localstack:
        image: localstack/localstack
        container_name: localstack_demo
        ports:
            - '4566-4599:4566-4599'
            - "9000:9000"
        environment:
            - SERVICES=sqs
            - DEFAULT_REGION=eu-central-1
            - DEBUG=${DEBUG- 1}
            - PORT_WEB_UI=9000
            - PORT_WEB_UI_INTERNAL=8080
            - DATA_DIR=/tmp/localstack/data
        volumes:
          - './.localstack:/tmp/localstack'
          - '/var/run/docker.sock:/var/run/docker.sock'
