
aws:
  accessKey: foo
  secretKey: bar
  region: us-east-1
  sns:
    topic-name: my-first-topic
    host: http://localhost:4575
  sqs:
    queue-name: my-new-queue
    host: http://localhost:4576

server:
  port: 8081

